const $ = (selector) => document.querySelector(selector);

const dom = {
    Body : $('#Body'),
    Message: $('#Message'),
    fightCount: $('#fightCount'),
    Monster_Side: $('#Monster_Side'),
    Monster_Name: $('#Monster_Name'),
    Monster_Image: $('#Monster_Image'),
    Monster_Health: $('#Monster_Health'),
    Start: $('#Start'),
    NewBtn: $('#NewBtn'),
    LoadBtn: $('#LoadBtn'),
    Combat: $('#Combat'),
    AttackBtn: $('#AttackBtn'),
    DefendBtn: $('#DefendBtn'),
    SaveBtn: $('#SaveBtn'),
    BagBtn: $('#BagBtn'),
    Shop: $('#Shop'),
    Bag: $('#Bag'),
    Player: $('#Player'),
    Player_Side: $('#Player_Side'),
    Health: $('#Health'),
    Attack: $('#Attack'),
    Defence: $('#Defence'),
    Gold: $('#Gold'),
    Bag: $('#Bag'),
    Item_List: $('#Item_List'),
    UseBtn: $('#UseBtn'),
    DropBtn: $('#DropBtn'),
}