const $ = (selector) => document.querySelector(selector);

const dom = {
    Body : $('#Body'),
    Message: $('#Message'),
    fightCount: $('#fightCount'),
    Monster_Side: $('#Monster_Side'),
    Monster_Name: $('#Monster_Name'),
    Monster_Image: $('#Monster_Image'),
    Monster_Health: $('#Monster_Health'),
    Start: $('#Start'),
    NewBtn: $('#NewBtn'),
    LoadBtn: $('#LoadBtn'),
    Combat: $('#Combat'),
    AttackBtn: $('#AttackBtn'),
    DefendBtn: $('#DefendBtn'),
    SaveBtn: $('#SaveBtn'),
    BagBtn: $('#BagBtn'),
    Shop: $('#Shop'),
    HealUPBtn: $('#HealUPBtn'),
    UpgradeBtn: $('#UpgradeBtn'),
    ExitShopBtn: $('#ExitShopBtn'),
    Bag: $('#Bag'),
    Bag_Buttons: $('#Bag_Buttons'),
    Player: $('#Player'),
    Player_Side: $('#Player_Side'),
    MaxHP: $('#MaxHP'),
    Health: $('#Health'),
    Attack: $('#Attack'),
    Defence: $('#Defence'),
    Gold: $('#Gold'),
    Bag_List: $('#Bag_List'),
    UseBtn: $('#UseBtn'),
    DropBtn: $('#DropBtn'),
    ExitBagBtn: $('#ExitBagBtn'),
    health: $('#health'),
    defence: $('#defence'),
    attack: $('#attack'),
}